name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
assignees:
  - Digitalroot
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: steps-Reproduce 
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: Tell us how to do it.
      value: |
      1. Go to '...' |
      2. Click on '....'
    validations:
      required: true      
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Digitalroot-Valheim/.github/blob/479002e346b72e826657aad54b2a9644dbdfaed1/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
