blank_issues_enabled: false
contact_links:
  - name: Official Valheim Discord
    url: https://discord.com/invite/valheim
    about: Get support at the Official Valheim Discord
  - name: Valheim Modding Discord
    url: https://discord.gg/UdWpADMGNg
    about: Get mod support at the Valheim Modding Discord
